# Very minimal setup, just for the sake of automated testing

version: 2.1

orbs:
  android: circleci/android@1.0.3

_defaults:
  - &restore_gradle_cache
    restore_cache:
      name: Restore Gradle Cache
      key: jars-{{ checksum "build.gradle" }}
  - &download_dependencies
    run:
      name: Download Dependencies
      command: ./gradlew androidDependencies
  - &save_gradle_cache
    save_cache:
      paths:
        - ~/.gradle
      key: jars-{{ checksum "build.gradle" }}
  - &run_tests
    run:
      name: Run Tests
      command: ./gradlew test
  - &run_connected_android_tests
      run:
        name:  Run Connected Android Tests
        command: ./gradlew connectedAndroidTest
  - &compress_report
    run:
      name: Compress Report
      command: tar -cvf report.tar -C ./build/reports .
  - &store_report
    store_artifacts:
      path: report.tar
      destination: report.tar
  - &store_test_results
    store_test_results:
      path: build/test-results

jobs:
  instrument_tests_level_29:
    executor:
      name: android/android-machine
      resource-class: large
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          system-image: system-images;android-29;google_apis;x86
    
  test_api_level_31:
    docker:
      - image: cimg/android:2021.10.2
    steps:
      - checkout
      - *restore_gradle_cache
      - *download_dependencies
      - *save_gradle_cache
      - *run_tests
      - *compress_report
      - *store_report
      - *store_test_results

  test_api_level_30:
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - *restore_gradle_cache
      - *download_dependencies
      - *save_gradle_cache
      - *run_tests
      - *compress_report
      - *store_report
      - *store_test_results

  test_api_level_29:
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - *restore_gradle_cache
      - *download_dependencies
      - *save_gradle_cache
      - *run_tests
      - *run_connected_android_tests
      - *compress_report
      - *store_report
      - *store_test_results

  test_api_level_28:
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout
      - *restore_gradle_cache
      - *download_dependencies
      - *save_gradle_cache
      - *run_tests
      - *run_connected_android_tests
      - *compress_report
      - *store_report
      - *store_test_results

workflows:
  version: 2
  test:
    jobs:
      - instrument_tests_level_29
      # - test_api_level_31
      # - test_api_level_30
      # - test_api_level_29
      # - test_api_level_28
